##端口配置
server:
  port: 8888

spring:
  datasource:
      url: jdbc:oracle:thin:@localhost:1521:ORCL
      username: kaifa
      password: zsl.com
      driver-class-name: oracle.jdbc.OracleDriver
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  servlet:
    ##修改上传图片大写
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
##reids
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1q2w3e4r
    ##连接超时
    timeout: 10000
    jedis:
      pool:
        ##连接池最大连接数
        max-active: 8
        ##连接池最大阻塞等待时间(负数表示没有限制)
        max-wait: -1
        ##连接池最大空闲数
        max-idle: 5
        ##连接池最下空闲数
        min-idle: 0

##mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.integral.mapper: debug


##fsdtDFS
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  ##测试环境
  tracker-list: localhost:22122
