##端口配置
server:
  port: 8888

spring:
  datasource:
    url: localhost
    username: mima
    password: mima
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1q2w3e4r
      ##连接超时
    timeout: 10000
    jedis:
      pool:
        ##连接池最大连接数
        max-active: 8
        ##连接池最大阻塞等待时间(负数表示没有限制)
        max-wait: -1
        ##连接池最大空闲数
        max-idle: 5
        ##连接池最下空闲数
        min-idle: 0


##mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.integral.mapper: debug

##fsdtDFS
fdfs:
  so-timeout: 1500
  connect-timeout: 600
#  tracker-list: localhost:22122
  ##测试环境
  tracker-list: localhost:22122
