##端口配置
server:
  port: 8888

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: kaifa
    password: zsl.com
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.integral.mapper: debug


##fsdtDFS
fdfs:
  so-timeout: 1500
  connect-timeout: 600
#  tracker-list: localhost:22122
  ##测试环境
  tracker-list: localhost:22122
